### ISSUE TITLE
Albatross event card can be used

### ISSUE THREAD

**Issue by Frostack** [Glyphack/tortuga#46]
**Describe the bug**
Albatross event card can be used while it's not usable at according to game rules!

**To Reproduce**
1. Reveal an albatross event card
2. Click on keep event card
3. Click on view my event cards
4. The use button exists

**Expected behavior**
API should always response with `gameStatus.playerGameInfo.eventCards[%albatross-index%].canUse` with `false` value

**Screenshots**
![Screenshot (45)](https://user-images.githubusercontent.com/47036679/88058686-0eeb3b80-cb79-11ea-808b-079bc255390e.png)

**Desktop:**
 - OS: windows 10
 - Browser: chrome
 - Version: ---

**Comment by Glyphack** [comment]
fixed in: https://github.com/Glyphack/tortuga/pull/47
